### ISSUE TITLE
Funky % parsing for attributes breaks basic Windows usage

### ISSUE THREAD

**Issue by jblaine** [sous-chefs/git#113]
### Cookbook version
5.0.2

### Chef-client version
12.12.15

### Platform Details
Windows Server 2012 R2

### Scenario:
Just trying to use the most basic part of the recipe: Install git client.

### Steps to Reproduce:
```
git_client 'default' do
  action :install
end
```

### Expected Result:
Git client to be installed.

### Actual Result:
```
    URI::InvalidURIError
    --------------------
    windows_package[Git version 2.7.4] (C:/chef/cache/cookbooks/git/libraries/pr
ovider_git_client_windows.rb line 11) had an error: URI::InvalidURIError: bad UR
I(is not URI?): https://github.com/git-for-windows/git/releases/download/v%2.7.4
.windows.1/Git-%2.7.4-32-bit.exe
```

**Comment by jblaine** [comment]
FWIW, in case anyone else hits this before it can be looked into, this complete alternative method used as a workaround gets me unblocked at least:
```
node.override['git']['version'] = '2.11.0'
node.override['git']['url'] = 'https://github.com/git-for-windows/git/releases/download/v2.11.0.windows.3/Git-2.11.0.3-64-bit.exe'
node.override['git']['checksum'] = 'c3897e078cd7f7f496b0e4ab736ce144c64696d3dbee1e5db417ae047ca3e27f'
node.override['git']['display_name'] = "Git version #{node['git']['version']}"

include_recipe 'git::default'
```

**Comment by grv87** [comment]
Bumping at this still not resolved issue I start to believe that Chef is dying..
Switch to Chocolatey for now.

**Comment by thirumoorthir** [comment]
this issue is fixed as i tested it here https://ci.appveyor.com/project/thirumoorthir/git/builds/36288908

@xorimabot please close this
